### ISSUE TITLE
Console error v1.3.0a

### ISSUE THREAD

**Issue by XxSTOZZYxX** [davelens/fvtt-party-resources#48] opened 2022-09-07 20:19 UTC
Foundry v10
Console error (see below)

```
Uncaught (in promise) Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[Detected 1 package: fvtt-party-resources]
    at SchemaField._validateType (commons.js:3630)
    at SchemaField.validate (commons.js:3357)
    at Setting.validate (commons.js:4994)
    at new DataModel (commons.js:4771)
    at new Document (commons.js:5310)
    at new BaseSetting (commons.js:9319)
    at new ClientDocumentMixin (foundry.js:12942)
    at new Setting (foundry.js:21144)
    at ClientSettings.get (foundry.js:2723)
    at ResourcesApi.get (modules/fvtt-party-resources/src/resources_api.mjs:37)
    at Function.all (modules/fvtt-party-resources/src/resources_list.mjs:3)
    at ResourcesApi.resources (modules/fvtt-party-resources/src/resources_api.mjs:82)
    at Function.getData (modules/fvtt-party-resources/src/resources_status_bar.mjs:6)
    at Function.render (modules/fvtt-party-resources/src/resources_status_bar.mjs:16)
    at Object.fn (modules/fvtt-party-resources/src/init.mjs:25)
    at Function.#call (foundry.js:688)
    at Function.callAll (foundry.js:645)
    at Game.setupGame (foundry.js:7769)
    at async Game._initializeGameView (foundry.js:8820)
    at async Game.initialize (foundry.js:7630)
```

**Comment by davelens** [comment] 2022-09-13 13:22
@XxSTOZZYxX I can't seem to reproduce this, though I'm familiar with the error. Foundry triggers this when data is requested through their `game.settings` object (which Party Resources does) with a key it can't match against any data. Seems to suggest that you tried to create a resource, and something happened along the way, but I can't be sure.

Do you recall what you were trying to do when you noticed this happening?

**Comment by XxSTOZZYxX** [comment] 2022-09-13 17:41
@davelens i don't recall specifically, no, but after flip flopping to v9 back to v10 i'm no longer able to reproduce so i'd say it's safe to disregard. if it pops again i'll keep ya posted but seems it might have been with the install itself.

**Comment by zoranac** [comment] 2022-09-15 09:45
I am having a very similar looking issue. It occurs when pressing the Party Resources button (nothing else happens for me). I have tried uninstalling and reinstalling the module but it still occurs. I have upgraded from v9 to v10 but never used the module while on v9.

![image](https://user-images.githubusercontent.com/5622164/190371880-5f60649d-ee58-44f4-832e-cef9a8b764c6.png)

**Comment by davelens** [comment] 2022-09-15 10:08
@zoranac Hrm. I'm thinking it depends what kind of values are stored in `game.settings`. whether you get validation errors or not. v10 came with `DataModel` changes that I *think* could cause this (the error seems to suggest it). 😕

I'll have to do some digging around. Problem is I'll only be able to look at it coming sunday at the earliest.

**Comment by iotech-fvtt** [comment] 2022-09-15 18:27
@davelens FWIW, I am getting exactly the same error as @zoranac when pressing the party resources button. Thanks for taking a look!

**Comment by davelens** [comment] 2022-09-15 19:12
@zoranac @XxSTOZZYxX @iotech-fvtt So I was able to take a quick look and made some adjustments. I *think* this is fixed in the 1.3.1 release I just made. Foundry 10 now requires a proper default value for all settings, which the module lacked (because things were less strict before). If you could check and verify, that'd be great.

If your dashboard opens it might show `RENAME ME` as a resource's name and/or one or more resources might have had their min/max values set to `-100` and `100` respectively. These were the values I believe to have been bugged.

**Comment by iotech-fvtt** [comment] 2022-09-15 20:41
@davelens works! Thank you so much! Now my players have to manage water on their trek across Chult in ToA. Muahahaha

I apologize if I came off as demanding a fix NOW, that was not my intention. I'm a mod author too, so I get how it can be. Thanks again!

**Comment by davelens** [comment] 2022-09-15 21:23
> I apologize if I came off as demanding a fix NOW, that was not my intention

No worries, I appreciate people reporting this. Sounds like your players could use an alchemy jug!

I'll keep this issue open for a few days longer.

**Comment by zoranac** [comment] 2022-09-15 23:18
@davelens This has fixed it for me as well, thanks!

**Comment by davelens** [comment] 2022-09-25 13:12
Alright, looks like no one's receiving this issue anymore. Thanks for the reports! Closing issue.

**Closed by davelens** 2022-09-25 13:12 UTC
