### ISSUE TITLE
[Improve UI]

### ISSUE THREAD

**Issue by brunocalado** [davelens/fvtt-party-resources#38] opened 2022-04-18 18:06 UTC
Hi.

The buttons +/- are very confusing. Can you improve the UI?

Suggestions

- Add a separator or border for each resource.
- Move the +/- to a better position. Side by side

![image](https://user-images.githubusercontent.com/4999783/163852828-e4d88330-9507-4ca3-9349-2de2ce0fdc49.png)

**Comment by davelens** [comment] 2022-04-20 14:45
@brunocalado Seems like the CSS isn't loading for you, as this is how it's supposed to look like:

![154817180-5dcb0c95-845f-4ef3-a8e8-9b734b2feda7](https://user-images.githubusercontent.com/221527/164256320-252dcc28-1eec-4f82-b6c2-6ae33074c927.jpeg)

I can't deduce why the CSS isn't loading for you, but typically the developer tools of the browser should give some clues (blocking resources, JS errors, ...). If you're running Foundry in a browser however, could you tell me which one including its version number? It could also be there's a module conflicting with Party Resources, which you can verify by disabling all modules except Party Resources.

**Comment by brunocalado** [comment] 2022-04-20 14:58
Active Modules:
----------
Alternative Pause Icon v;
Brazilian Portuguese [SWADE] v;
Chat Images v;
CodeMirror vfvtt4;
Compendium Folders v;
Custom Css v;
DFreds Droppables v;
Dice So Nice! v;
Dice Tray v;
Dungeon Draw v;
Image Hover v;
Journal to Canvas Slideshow - Display Journal Art on the Canvas v;
Kandashi's Fluid Canvas v;
lib - Color Settings v;
libWrapper v0;
Macros for SWADE v;
Minimal UI v;
Narrator Tools v;
Party Resources v;
Permission Viewer v;
Pings v;
Potato Or Not v;
Quick Insert - Search Widget v;
✋ Raise My Hand v;
Roll of Fate v;
Savage Worlds Adventure Edition Core Rules v;
Settings Extender v;
Simple Name Generator v;
socketlib v;
Sweet Nothings v;
Tidy UI - Game Settings v;
Tokenizer v;
Warp Gate v;

Chrome 
Win 10


![image](https://user-images.githubusercontent.com/4999783/164260220-aebf094f-313d-4a5e-be2e-6188ec18ca56.png)

**Comment by brunocalado** [comment] 2022-04-20 16:17
![image](https://user-images.githubusercontent.com/4999783/164276645-0d1dbe78-7f8c-4863-87af-0b1e1d50ec5b.png)

**Comment by davelens** [comment] 2022-04-20 23:53
@brunocalado Are there perhaps any errors present in the Console tab of the dev tools?

**Comment by davelens** [comment] 2022-05-10 19:16
@brunocalado Bump. Have you seen my previous question / did you get this resolved / can I close this? :)

**Comment by brunocalado** [comment] 2022-05-10 19:50
I'll check It out next week.

Em ter, 10 de mai de 2022 16:16, Dave Lens ***@***.***>
escreveu:

**Comment by brunocalado** [comment] 2022-05-13 11:07
GM View - Google Chrome
![image](https://user-images.githubusercontent.com/4999783/168270936-db447ebb-3e7b-4c02-82dc-81655436bcac.png)

Player View - Ungoogled
![image](https://user-images.githubusercontent.com/4999783/168271020-ea08d2e2-63ae-4d7e-8df1-2d2247186a17.png)

**Comment by davelens** [comment] 2022-09-16 20:17
@brunocalado Sorry for taking this long, 😞 I'm in the process of reviewing the current issue list, now that Foundry v10 was released. I still can't reproduce this in Google Chrome, and no other similar reports seem to have come in :-/ My guess is still there is (was) another mod in conflict with the styles of Party Resources. If you still have this issue with all other mods disabled, it might be a Google Chrome extension with the CSS. Impossible to tell which one though.

**Comment by davelens** [comment] 2022-09-25 13:15
Closing this issue due to staleness. If it still persists in v10, please disable all modules except Party Resources and see if that works. If it does, re-enable the other modules one by one to see where the conflict lies.

**Closed by davelens** 2022-09-25 13:15 UTC
Labels: question, on hold
